# Generated by Django 5.1.1 on 2024-10-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=0, upload_to='category_image/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
