# Generated by Django 5.1.1 on 2024-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_total_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Credit Card', max_length=50),
        ),
    ]
